print('\n')
print("o tipo de dado  informado é: ", int("1"), type(int("1")))
print("o resultado da soma é: ", int('1') + 1)
print("o resultado da soma é: ", float('1') + 1)
print("o resultado da soma é: ", bool('1') != 1)
print("o resultado da conversão é o ano de: ", str('20') + '24')